apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: paperclip-prod

resources:
  - ../../base
  - namespace.yaml

images:
  - name: paperclip
    newName: image-registry.openshift-image-registry.svc:5000/paperclip-prod/paperclip
    newTag: latest

patches:
  - path: patches/deployment.yaml
  - path: patches/secretstore.yaml
  - path: patches/configmap.yaml
  - path: patches/route.yaml
