apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - imagestream.yaml
  - buildconfig.yaml
  - objectbucketclaim.yaml
  - secretstore.yaml
  - externalsecret.yaml
  - configmap.yaml
  - company-ca-configmap.yaml
  - pvc.yaml
  - deployment.yaml
  - service.yaml
  - route.yaml
  - poddisruptionbudget.yaml
  - networkpolicy.yaml

commonLabels:
  app.kubernetes.io/name: paperclip
  app.kubernetes.io/part-of: paperclip
